Graph

In [2]:
import torch 
print('GPU available:', torch.cuda.is_available())

# Forward pass
x = torch.tensor(2.0, requires_grad=True) # requires_grad=True allows tracking of operations on this tensor
y = x ** 2 
z = torch.sin(y)
print(f"Output z: {z.item()}") 

# Backward pass
z.backward() # dz/dx=dz/du*du/dx
print(f"Gradient of z with respect to x: {x.grad.item()}") # Gradient. 2*x*cos(x^2)

GPU available: True
Output z: -0.756802499294281
Gradient of z with respect to x: -2.614574432373047


Shape

In [2]:
import tensorflow as tf

input_shape = (2, 3)
x1 = tf.random.normal(input_shape, mean=0.0, stddev=1.0)
x2 = tf.random.normal(input_shape)
y = tf.keras.layers.Add()([x1, x2])

print(x1)
print(x2)
print(y.shape)
print(y)


tf.Tensor(
[[-0.5755069  -1.7246705   0.5698334 ]
 [-1.2045128  -0.14158128 -0.7437579 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[-0.00790841 -0.25614816 -0.9186853 ]
 [-0.7668161  -1.3055285   0.22155765]], shape=(2, 3), dtype=float32)
(2, 3)
tf.Tensor(
[[-0.5834153  -1.9808187  -0.34885192]
 [-1.971329   -1.4471098  -0.5222002 ]], shape=(2, 3), dtype=float32)


In [6]:
model = tf.keras.Sequential()
rs = tf.keras.layers.Reshape((3, 4), input_shape=(12,))
model.add(rs)
s = model.output_shape  # (None, 3, 4). # (mini batch size, 3, 4)
print(s)
model.add(tf.keras.layers.Reshape((-1, 2, 2)))   # (None, 3, 2, 2)
s = model.output_shape  # (None, 3, 4)
print(s)

(None, 3, 4)
(None, 3, 2, 2)


c:\Users\MAC\.conda\envs\venv_lmm\Lib\site-packages\keras\src\layers\reshaping\reshape.py:39: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


PyTorch shape

In [ ]:
print('reshape')
x = torch.arange(24).reshape(2, 3, 4) # torch.rand(2, 3, 4)  # [2, 3, 4] 
s = x.shape
print(s)
print(x)
y = x.view(2, -1)  # [2, 12] 
print(y.shape)
print(y)
z = y.unsqueeze(0) # [1, 2, 12]
print('unsqueeze=', z.shape)
print(z)
z = z.squeeze(0) # [2, 12]
print('squeeze=', z.shape)
print(z)

GPU available: True
reshape
torch.Size([2, 3, 4])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 12])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
unsqueeze= torch.Size([1, 2, 12])
tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]]])
squeeze= torch.Size([2, 12])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])


In [7]:
print('\npermute')
x = torch.arange(0, 5).reshape(1, 5)
print(x.shape)
print(x)
y = x.transpose(0, 1)  # [5, 1].
print('transpose=', y.shape)
print(y)
z = x.permute(1, 0)  # [5, 1]. 
print('permute=', z.shape)
print(z)

x = torch.arange(0, 3 * 32 * 32).reshape(3, 32, 32) # (3, 32, 32) > permute(2, 1, 0) > (32, 32, 3)
print(x.shape)
z = x.permute(2, 1, 0)
print(z.shape)


permute
torch.Size([1, 5])
tensor([[0, 1, 2, 3, 4]])
transpose= torch.Size([5, 1])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
permute= torch.Size([5, 1])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
torch.Size([3, 32, 32])
torch.Size([32, 32, 3])
